version: '3.7'

volumes:
    grafana_data: {}
    prometheus_data: {}

networks:
  yearn-exporter:

services:
  yearn-exporter-v1:
    build: .
    command: brownie run yearn exporter_v1 --network mainnet
    environment:
      - WEB3_INFURA_PROJECT_ID=${WEB3_INFURA_PROJECT_ID}
    networks:
      - yearn-exporter
    restart: always

  yearn-exporter-v2:
    build: .
    command: brownie run yearn exporter_v2 --network mainnet
    environment:
      - WEB3_INFURA_PROJECT_ID=${WEB3_INFURA_PROJECT_ID}
    networks:
      - yearn-exporter
    restart: always

  yearn-exporter-experimental:
    build: .
    command: brownie run yearn exporter_experimental --network mainnet
    environment:
      - WEB3_INFURA_PROJECT_ID=${WEB3_INFURA_PROJECT_ID}
    networks:
      - yearn-exporter
    restart: always

  prometheus:
    image: prom/prometheus:v2.23.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - yearn-exporter
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - yearn-exporter
    restart: always
