{
 "title": "Are the Exporters Working?",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "V1 Vaults",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"yearn-v1\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "V2 Vaults",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"yearn-v2\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "graph",
   "description": "1 is up, 0 is down.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"yearn-v1\"}",
     "legendFormat": "v1 Vaults Exporter"
    },
    {
     "expr": "up{job=\"yearn-v2\"}",
     "legendFormat": "v2 Vaults Exporter"
    },
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "Prometheus"
    }
   ]
  }
 ]
}